# Generated by Django 4.1.13 on 2023-11-15 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('field_name_1', models.CharField(max_length=255)),
                ('field_name_2', models.CharField(max_length=255)),
            ],
        ),
    ]
